version: "3.9"

services:
  app:
    env_file: .env
    environment:
      - DEV_CONTAINER=1
    build: 
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        GIT_AUTHOR_NAME: ${GIT_AUTHOR_NAME}
        GIT_AUTHOR_EMAIL: ${GIT_AUTHOR_EMAIL}
        PY_VER: "3.11"
    network_mode: "bridge"
    volumes:
      - type: bind
        source: ../
        target: /workspace/libreoffice_python
      - type: volume
        source: virtual_env
        target: /workspace/libreoffice_python/.venv

    # user root is for file sharing. root user is the current user on the host
    # and the bind volume for libreoffice_python will not work unless root.
    user: root
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"  
    container_name: libreoffice_python_container

  libreoffice:
    network_mode: "bridge"
    # env_file: user.env
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile.lo
    # user: root
    container_name: libreoffice
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - TZ=Etc/UTC
      - PUID=0
      - PGID=0
      - CONFIG_DIR=/config
      - DEV_CONTAINER=1
    volumes:
      - type: volume
        source: lo_config
        target: /config
      - type: bind
        source: ../src/macros
        target: /config/.config/libreoffice/4/user/Scripts/python
      - type: bind
        source: ../code_docs
        target: /config/Code Documents
    
    ports:
      - 3002:3000
      - 3003:3001
    restart: unless-stopped

volumes:
  virtual_env:
  lo_config:
