version: "3.9"

services:
  libreoffice_app:
    env_file: .env
    network_mode: "bridge"
    # env_file: user.env
    build:
      context: ../../
      dockerfile: .devcontainer/app_mode/Dockerfile
      args:
        GIT_AUTHOR_NAME: ${GIT_AUTHOR_NAME}
        GIT_AUTHOR_EMAIL: ${GIT_AUTHOR_EMAIL}
    # user: root
    container_name: libreoffice_app
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - TZ=Etc/UTC
      - PUID=0
      - PGID=0
      - CONFIG_DIR=/config
      - DEV_CONTAINER=1
    volumes:
      - type: bind
        source: ../../
        target: /workspace/libreoffice_python_app
      - type: bind
        source: ../../Documents
        target: /root/Documents
      - type: bind
        source: ../../macro
        target: /root/.config/libreoffice/4/user/Scripts/python
      - type: volume
        source: app_lo_config
        target: /config
      - type: volume
        source: app_virtual_env
        target: /workspace/libreoffice_python_app/.venv
    
    ports:
      - 3002:3000
      - 3003:3001
    restart: unless-stopped

volumes:
  app_virtual_env:
  app_lo_config:
